package me.app.pojo;

import java.util.Date;

public class AdPromotion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.appId
     *
     * @mbggenerated
     */
    private Long appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.adPicPath
     *
     * @mbggenerated
     */
    private String adpicpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.adPV
     *
     * @mbggenerated
     */
    private Long adpv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.carouselPosition
     *
     * @mbggenerated
     */
    private Integer carouselposition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.modifyBy
     *
     * @mbggenerated
     */
    private Long modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ad_promotion.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.id
     *
     * @return the value of ad_promotion.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.id
     *
     * @param id the value for ad_promotion.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.appId
     *
     * @return the value of ad_promotion.appId
     *
     * @mbggenerated
     */
    public Long getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.appId
     *
     * @param appid the value for ad_promotion.appId
     *
     * @mbggenerated
     */
    public void setAppid(Long appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.adPicPath
     *
     * @return the value of ad_promotion.adPicPath
     *
     * @mbggenerated
     */
    public String getAdpicpath() {
        return adpicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.adPicPath
     *
     * @param adpicpath the value for ad_promotion.adPicPath
     *
     * @mbggenerated
     */
    public void setAdpicpath(String adpicpath) {
        this.adpicpath = adpicpath == null ? null : adpicpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.adPV
     *
     * @return the value of ad_promotion.adPV
     *
     * @mbggenerated
     */
    public Long getAdpv() {
        return adpv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.adPV
     *
     * @param adpv the value for ad_promotion.adPV
     *
     * @mbggenerated
     */
    public void setAdpv(Long adpv) {
        this.adpv = adpv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.carouselPosition
     *
     * @return the value of ad_promotion.carouselPosition
     *
     * @mbggenerated
     */
    public Integer getCarouselposition() {
        return carouselposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.carouselPosition
     *
     * @param carouselposition the value for ad_promotion.carouselPosition
     *
     * @mbggenerated
     */
    public void setCarouselposition(Integer carouselposition) {
        this.carouselposition = carouselposition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.startTime
     *
     * @return the value of ad_promotion.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.startTime
     *
     * @param starttime the value for ad_promotion.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.endTime
     *
     * @return the value of ad_promotion.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.endTime
     *
     * @param endtime the value for ad_promotion.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.createdBy
     *
     * @return the value of ad_promotion.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.createdBy
     *
     * @param createdby the value for ad_promotion.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.creationDate
     *
     * @return the value of ad_promotion.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.creationDate
     *
     * @param creationdate the value for ad_promotion.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.modifyBy
     *
     * @return the value of ad_promotion.modifyBy
     *
     * @mbggenerated
     */
    public Long getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.modifyBy
     *
     * @param modifyby the value for ad_promotion.modifyBy
     *
     * @mbggenerated
     */
    public void setModifyby(Long modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ad_promotion.modifyDate
     *
     * @return the value of ad_promotion.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ad_promotion.modifyDate
     *
     * @param modifydate the value for ad_promotion.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}