package me.app.pojo;

import java.util.Date;

public class DataDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.typeCode
     *
     * @mbggenerated
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.typeName
     *
     * @mbggenerated
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.valueId
     *
     * @mbggenerated
     */
    private Long valueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.valueName
     *
     * @mbggenerated
     */
    private String valuename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.createdBy
     *
     * @mbggenerated
     */
    private Long createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.creationDate
     *
     * @mbggenerated
     */
    private Date creationdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.modifyBy
     *
     * @mbggenerated
     */
    private Long modifyby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_dictionary.modifyDate
     *
     * @mbggenerated
     */
    private Date modifydate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.id
     *
     * @return the value of data_dictionary.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.id
     *
     * @param id the value for data_dictionary.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.typeCode
     *
     * @return the value of data_dictionary.typeCode
     *
     * @mbggenerated
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.typeCode
     *
     * @param typecode the value for data_dictionary.typeCode
     *
     * @mbggenerated
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.typeName
     *
     * @return the value of data_dictionary.typeName
     *
     * @mbggenerated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.typeName
     *
     * @param typename the value for data_dictionary.typeName
     *
     * @mbggenerated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.valueId
     *
     * @return the value of data_dictionary.valueId
     *
     * @mbggenerated
     */
    public Long getValueid() {
        return valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.valueId
     *
     * @param valueid the value for data_dictionary.valueId
     *
     * @mbggenerated
     */
    public void setValueid(Long valueid) {
        this.valueid = valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.valueName
     *
     * @return the value of data_dictionary.valueName
     *
     * @mbggenerated
     */
    public String getValuename() {
        return valuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.valueName
     *
     * @param valuename the value for data_dictionary.valueName
     *
     * @mbggenerated
     */
    public void setValuename(String valuename) {
        this.valuename = valuename == null ? null : valuename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.createdBy
     *
     * @return the value of data_dictionary.createdBy
     *
     * @mbggenerated
     */
    public Long getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.createdBy
     *
     * @param createdby the value for data_dictionary.createdBy
     *
     * @mbggenerated
     */
    public void setCreatedby(Long createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.creationDate
     *
     * @return the value of data_dictionary.creationDate
     *
     * @mbggenerated
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.creationDate
     *
     * @param creationdate the value for data_dictionary.creationDate
     *
     * @mbggenerated
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.modifyBy
     *
     * @return the value of data_dictionary.modifyBy
     *
     * @mbggenerated
     */
    public Long getModifyby() {
        return modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.modifyBy
     *
     * @param modifyby the value for data_dictionary.modifyBy
     *
     * @mbggenerated
     */
    public void setModifyby(Long modifyby) {
        this.modifyby = modifyby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_dictionary.modifyDate
     *
     * @return the value of data_dictionary.modifyDate
     *
     * @mbggenerated
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_dictionary.modifyDate
     *
     * @param modifydate the value for data_dictionary.modifyDate
     *
     * @mbggenerated
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }
}