package me.app.dao;

import me.app.pojo.AppCategory;

public interface AppCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated
     */
    int insert(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated
     */
    int insertSelective(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated
     */
    AppCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppCategory record);
}