package me.app.dao;

import me.app.pojo.AppInfo;
import me.app.pojo.DataDictionary;
import org.springframework.stereotype.Repository;

@Repository
public interface DataDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dictionary
     *
     * @mbggenerated
     */
    int insert(DataDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(DataDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dictionary
     *
     * @mbggenerated
     */
    DataDictionary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DataDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DataDictionary record);

    String APP_FLATFORM(AppInfo appInfo);

    String AppStatus(AppInfo appInfo);
}